import{a as h,i as l,S as L}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const y=(r,t)=>{const o={params:{key:"48272938-5d16b358faf0ec3baa9736196",q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return h.get("https://pixabay.com/api/",o)},f=r=>`
   <a href="${r.largeImageURL}">
        <li class="gallary-card">
            <img class="gallary-img" src="${r.webformatURL}" alt=""> </img>
            <div class="description">
                <p>Likes ${r.likes}</p>
                <p>Views ${r.views}</p>
                <p>Comments ${r.comments}</p>
                <p>Downloads ${r.downloads}</p>
            </div>
        </li>
    </a>`,p=document.querySelector(".search-form"),u=document.querySelector(".gallery"),n=document.querySelector(".loader"),d=document.querySelector(".btn-load-more");let i=1,c="";n.style.display="none";const b=async r=>{try{if(r.preventDefault(),n.style.display="block",c=r.currentTarget.elements.user_query.value.trim(),c===""){l.show({title:"Error",message:"Поле пошуку порожнє, заповніть поле пошуку!",position:"center"});return}i=1;const t=await y(c,i);console.log("🚀 ~ response:",t),t.data.total===0&&(l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),u.innerHTML="",p.reset()),p.reset(),t.data.totalHits>1&&(d.classList.remove("is-hidden"),d.addEventListener("click",g));const o=t.data.hits.map(e=>f(e)).join("");u.innerHTML=o,n.style.display="none",new L(".gallery a").refresh();return}catch{l.error({title:"Error",message:"Error!",position:"center"})}},g=async r=>{try{n.style.display="block",i++;const t=await y(c,i),o=t.data.hits.map(a=>f(a)).join("");u.insertAdjacentHTML("beforeend",o),n.style.display="none",i>t.data.totalHits&&(d.classList.add("is-hidden"),d.removeEventListener("click",g))}catch{l.error({title:"Error",message:"Error!",position:"center"})}};p.addEventListener("submit",b);
//# sourceMappingURL=index.js.map
