import{a as v,i as l,S as g}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))m(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&m(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function m(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const f=(s,r)=>{const a={params:{key:"48272938-5d16b358faf0ec3baa9736196",q:s,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return v.get("https://pixabay.com/api/",a)},h=s=>`
   <a href="${s.largeImageURL}">
        <li class="gallary-card">
            <img class="gallary-img" src="${s.webformatURL}" alt=""> </img>
            <div class="description">
                <p>Likes ${s.likes}</p>
                <p>Views ${s.views}</p>
                <p>Comments ${s.comments}</p>
                <p>Downloads ${s.downloads}</p>
            </div>
        </li>
    </a>`,p=document.querySelector(".search-form"),y=document.querySelector(".gallery"),d=document.querySelector(".loader"),o=document.querySelector(".btn-load-more");let c=1,u="";const L=15;d.style.display="none";const E=async s=>{try{if(s.preventDefault(),d.style.display="block",u=s.currentTarget.elements.user_query.value.trim(),u===""){l.show({title:"Error",message:"Поле пошуку порожнє, заповніть поле пошуку!",position:"center"}),o.classList.add("is-hidden"),o.removeEventListener("click",n);return}c=1;const r=await f(u,c);r.data.total===0&&(l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),y.innerHTML="",o.classList.add("is-hidden"),o.removeEventListener("click",n),p.reset()),p.reset(),r.data.totalHits>1&&(o.classList.remove("is-hidden"),o.addEventListener("click",n)),r.data.total<=L&&(o.classList.add("is-hidden"),o.removeEventListener("click",n));const a=r.data.hits.map(e=>h(e)).join("");y.innerHTML=a,d.style.display="none",new g(".gallery a").refresh();return}catch{l.error({title:"Error",message:"Error!",position:"center"})}},n=async s=>{try{d.style.display="block",c++;const r=await f(u,c),a=r.data.hits.map(t=>h(t)).join("");y.insertAdjacentHTML("beforeend",a),new g(".gallery a").refresh(),setTimeout(()=>{const t=document.querySelectorAll(".gallary-card");if(t.length>0){const i=t[0].getBoundingClientRect().height;window.scrollBy({top:i*2,left:0,behavior:"smooth"})}},300);const e=Math.ceil(r.data.totalHits/L);if(c>=e){d.style.display="none",l.show({title:"Error",message:"We're sorry, but you've reached the end of search results",position:"topRight"}),o.classList.add("is-hidden"),o.removeEventListener("click",n);return}}catch{l.error({title:"Error",message:"Error!",position:"center"})}};p.addEventListener("submit",E);
//# sourceMappingURL=index.js.map
