import{a as L,i as a,S as y}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const g=(r,t)=>{const o={params:{key:"48272938-5d16b358faf0ec3baa9736196",q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return L.get("https://pixabay.com/api/",o)},f=r=>`
   <a href="${r.largeImageURL}">
        <li class="gallary-card">
            <img class="gallary-img" src="${r.webformatURL}" alt=""> </img>
            <div class="description">
                <p>Likes ${r.likes}</p>
                <p>Views ${r.views}</p>
                <p>Comments ${r.comments}</p>
                <p>Downloads ${r.downloads}</p>
            </div>
        </li>
    </a>`,p=document.querySelector(".search-form"),d=document.querySelector(".gallery"),n=document.querySelector(".loader"),m=document.querySelector(".btn-load-more");document.querySelectorAll(".gallary-card");let i=1,c="";const b=15;n.style.display="none";const E=async r=>{try{if(r.preventDefault(),n.style.display="block",c=r.currentTarget.elements.user_query.value.trim(),c===""){a.show({title:"Error",message:"Поле пошуку порожнє, заповніть поле пошуку!",position:"center"});return}i=1;const t=await g(c,i);t.data.total===0&&(a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),d.innerHTML="",p.reset()),p.reset(),t.data.totalHits>1&&(m.classList.remove("is-hidden"),m.addEventListener("click",h));const o=t.data.hits.map(e=>f(e)).join("");d.innerHTML=o,n.style.display="none",new y(".gallery a").refresh();return}catch{a.error({title:"Error",message:"Error!",position:"center"})}},h=async r=>{try{n.style.display="block",i++;const t=await g(c,i),o=t.data.hits.map(s=>f(s)).join("");d.insertAdjacentHTML("beforeend",o),new y(".gallery a").refresh();const e=Math.ceil(t.data.totalHits/b);if(i>=e){n.style.display="none",a.show({title:"Error",message:"We're sorry, but you've reached the end of search results",position:"topRight"}),m.classList.add("is-hidden"),m.removeEventListener("click",h);return}}catch{a.error({title:"Error",message:"Error!",position:"center"})}};p.addEventListener("submit",E);const{heigt:v}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:v*2,left:0,behavior:"smooth"});
//# sourceMappingURL=index.js.map
